services:
  - type: web
    name: visionforge
    runtime: python
    region: oregon
    plan: free
    branch: main
    rootDir: ./project
    buildCommand: |
      pip install -r requirements.txt
      chmod +x build_frontend.sh
      ./build_frontend.sh
      python manage.py collectstatic --no-input
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: RENDER_EXTERNAL_HOSTNAME
        sync: false
      - key: AI_PROVIDER
        value: gemini
      - key: GEMINI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.12.5
      - key: VITE_API_URL
        value: /api
